source 'http://rubygems.org'

gem 'rails', '3.2.1'
gem 'mysql2'
gem 'authlogic'
gem 'jquery-rails'
gem 'gmaps4rails'
gem 'execjs'
gem 'libv8','3.3.10.4'
gem 'therubyracer','0.9.9'
gem 'dynamic_form'
gem 'gon', '3.0.5'
gem 'rails_admin'
gem 'geocoder'
gem 'thin'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
	gem 'rspec', '>= 2.0.0.beta.20'
  gem 'rspec-rails', '>= 2.0.0.beta.20'
	gem 'autotest'
	gem 'webrat'
	gem 'annotate'
end

gem "devise"

group :development, :test do
  gem 'railroady'
end